---
# defaults file for cis-rhel8


cis_name: Red Hat Enterprise Linux 8

cis_version: Red Hat Enterprise Linux 8 Version 2.1

cis_rules:
  "1":
      name: 1 Ensure Red Hat Subscription Manager connection is configured
      remediation_method: playbook
      server_lv: Level 1
      verification_method: script
  "5":
      name: 5 Ensure permissions on all logfiles are configured
      remediation_method: playbook
      server_lv: Level 1
      verification_method: script
