---


- name: Prepare the variables for CIS tasks
  ansible.builtin.include_tasks: pre_work.yaml

- debug:
    msg: "selection - {{ selection }}"

- debug:
    msg: "cis_rules.keys - {{ cis_rules.keys()|list }}"

- debug:
    msg: "match"
  when: 
  - selection|string in cis_rules.keys()|list

- name:  trigger verificaiton task when selction ends with '.' - substring match
  block:
    - name: remove special meaning for . in selection 
      ansible.builtin.set_fact:
        filter_str: "^{{ selection.replace('.', '\\.') }}"

    - name: trigger the CIS action for list of policies
      ansible.builtin.include_tasks: actions.yaml
      loop: "{{ cis_rules.keys() | select('match', filter_str) | list }}"
      loop_control:
        loop_var: cis_item
  when: 
  - selection|string is match("^([0-9]|\\.)+\\.$")

- name:  trigger verificaiton task when selction exactly match
  block:
    - name: Ensure the item "{{ selection }}" valid
      ansible.builtin.assert:
        that:
          - selection|string in cis_rules.keys()|list
        fail_msg: "{{ selection }} is not valid."
        success_msg: "{{ selection }} is valid."

    - name: trigger the CIS action for single policies
      ansible.builtin.include_tasks: actions.yaml
      vars:
        cis_item: "{{ selection }}"
      when: 
      - selection|string in cis_rules.keys()|list
  when: 
  - not selection|string is match("^([0-9]|\\.)+\\.$")
