---
#- name: import CIS rule data
#  include_tasks: import_cis_base.yaml
#  loop: "{{ cis }}"
#  loop_control:
#    loop_var: cis_item
#  no_log: true

  #- debug: var=dicts
  #- copy:
  #    content: "{{ dicts | to_nice_yaml }}"
  #    dest: /tmp/test.yaml
  #

- name: set report html file name
  ansible.builtin.set_fact:
    rpt_file_v1: "{{ rpt_path_v1 }}/{{ ansible_hostname }}.html"
    rpt_file_v2: "{{ rpt_path_v2 }}/{{ ansible_hostname }}.html"
    rpt_file_v3: "{{ rpt_path_v3 }}/{{ ansible_hostname }}.html"

- name: rotate report files
  ansible.builtin.shell: |
    [[ -d {{ rpt_path_v1 }} ]] || mkdir -p {{ rpt_path_v1 }}
    [[ -d {{ rpt_path_v2 }} ]] || mkdir -p {{ rpt_path_v2 }}
    [[ -d {{ rpt_path_v3 }} ]] || mkdir -p {{ rpt_path_v3 }}
    [[ -f {{ rpt_file_v3 }} ]] && [[ -f {{ rpt_file_v2 }} ]] && mv {{ rpt_file_v2 }} {{ rpt_file_v1 }}
    [[ -f {{ rpt_file_v3 }} ]] && mv {{ rpt_file_v3 }} {{ rpt_file_v2 }}
    exit 0
  become: no
  delegate_to: localhost

- name: Get end time
  block:
    - ansible.builtin.setup:
        filter: ansible_date_time
      register: result
    - ansible.builtin.set_fact:
        end_time: "{{ lookup('pipe','date \"+%T %Z %F\"') }}"
  delegate_to: localhost
  become: no

- name: create html report
  ansible.builtin.template:
    src: cis-report.html.j2
    dest: "/tmp/{{ ansible_hostname }}.html"
    #dest: "{{ rpt_file_v3 }}"
  #delegate_to: localhost
  become: no

